### ISSUE TITLE
Erro ao criar produto com categoria

### ISSUE THREAD

**Issue by brunoapimentel** [leorush2112/ecommercerush#1]
Caso você envie uma categoria inexistente ao criar um produto, essa linha irá gerar uma `NoSuchElementException`:

https://github.com/leorush2112/ecommercerush/blob/61ae648eaa7b7133fc11326dcb4293dfed7e855b/src/main/java/com/ecommerce/rush/service/LojaService.java#L32

https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html#get--

**Comment by felipem11** [comment]
Oi Bruno, nessa linha esta retornando o erro pq basicamente esta dando um get num Optional empty.
Talvez vc possa mudar pra algo assim, caso nao encontre a categoria, lanca uma exception, assim vc pode tratar no seu front, e caso encontre, sempre retorna uma categoria e vc nao precisa se preocupar nos consumidores de metodo

```java
	public Categoria buscarCategoria(int id) {
		return categorias.stream().filter(c -> c.getId() == id)
				.findFirst()
				.orElseThrow(() -> new CategoriaNaoEncontradaException(id));
	}
```

CategoriaNaoEncontradaException.class
```java
@ResponseStatus(HttpStatus.NOT_FOUND)
class CategoriaNaoEncontradaException extends RuntimeException{
	public CategoriaNaoEncontradaException(int id) {
		super(String.format("Categoria %d não encontrada", id));
	}
}
```

E poderia consumir algo assim, com menos objetos sendo criados
```java
	public Produto criarProduto(Produto produto) {
		List<Categoria> categoriasPost = new ArrayList<>();

		produto.getCategoriaIds().forEach(categoriaId ->
				categoriasPost.add(categoriaRepository.buscarCategoria(categoriaId)));
		produto.setCategoriasPrd(categoriasPost);
		produtoRepository.inserirProduto(produto);
		
		return produto;
	}
	
```
